### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError

### ISSUE THREAD

**Issue by yi1873** [MicrobeLab/DeepMicrobes#1]
Training error: "tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot add tensor to the batch: number of elements does not match. Shapes are: [tensor]: [2516], [batch]: [2337]
         [[{{node IteratorGetNext}}]]
During handling of the above exception, another exception occurred".  

How to solve this problem?

**Comment by MicrobeLab** [comment]
Thank you for your interest in DeepMicrobes. Please provide a demo of your training data (fastq/fasta) and the commands used to produce training set and train the model.

**Comment by yi1873** [comment]
http://note.youdao.com/noteshare?id=10c2065724c8d4c2276bbc2ccef4b433

**Comment by MicrobeLab** [comment]
Currently DeepMicrobes only supports training only sequences with the same length. Will allow users to specify the maximum sequence length and zero-padding the sequences shorter than that length in the next version. Alternatively, you could trim your sequences to a fix length before converting them to TFRecord. Thanks.

**Comment by MicrobeLab** [comment]
The new version of DeepMicrobes can be trained and tested on variable-length sequences.
