### ISSUE TITLE
Optimal hyperparameters

### ISSUE THREAD

**Issue by ag14774** [MicrobeLab/DeepMicrobes#2]
Where can I find the optimal hyperparameters if I want to train the network from scratch?

Thanks

**Comment by MicrobeLab** [comment]
The optimal hyperparameters are set as default values. We also summarized the optimal hyperparameters that we used to train DeepMicrobes [here](https://github.com/MicrobeLab/DeepMicrobes/blob/master/hyperparameters/hyperparameters_DeepMicrobes.txt). 

Thanks
