### ISSUE TITLE
Inquiry Regarding DeepMicrobes Installation and Usage

### ISSUE THREAD

**Issue by Praneet-Prabhanjan** [MicrobeLab/DeepMicrobes#37]
Dear Authors and researchers,

I am currently exploring the intersection of deep learning and metagenomics, and this project aligns with my research interests.  However, I am encountering some challenges related to the installation of dependencies without the use of Anaconda/Conda.  I believe that your insights and experience would be invaluable in helping me navigate these challenges.

1. **Conda-Independent Installation of TensorFlow 1.9.0**
Is there a way to install TensorFlow-base 1.9.0,  without relying on Conda? If there are customized versions or alternative methods available, I would appreciate your guidance.  Can you mention the significance of Tf-base = 1.9.0 How important is it? 

2. **Compatibility with TensorFlow 2**
Is it feasible to use TensorFlow 2 with DeepMicrobes? Are there any known issues or solutions for compatibility?

3. **Use of Higher Versions of CUDA Toolkit/cuDNN**
Can higher versions of the CUDA Toolkit and cuDNN be used with DeepMicrobes to optimize performance? If so, which versions are recommended?

4. **Alternative Solutions for Installation**
Are there alternative solutions or workarounds for installing the necessary dependencies without using Anaconda/Conda? Manual installation has been challenging, and I am seeking possible alternatives.

Thank you

**Comment by MicrobeLab** [comment]
Hi, thank you for your interest to our work.
1. You may install it using pip: pip install tensorflow==1.9.0; The codes of TF differ a lot across different versions.
2. TF1 and TF2 differs a lot. https://github.com/MicrobeLab/DeepMicrobes/issues/22
3. Versions of CUDA and TF should match.
4. All python modules can be installed using other approaches such as pip.
