### ISSUE TITLE
tfrec_train_kmer.sh tries to create directories in such a way that script fails.

### ISSUE THREAD

**Issue by lambertsbennett** [MicrobeLab/DeepMicrobes#7]
When using the helper script to convert the sequence fasta file that I'm interested in using for training I run the following command:

```
./tfrec_train_kmer.sh -i ~/Documents/Projects/NLP-binning-approaches/data/Combined_transcripts.fasta 
-v ~/Documents/Projects/NLP-binning-approaches/data/mmetsp.vocab -o mmetsp.train.tfrec -k 12
```
Regardless of whether I split sequences or not I get the following output:

1. Shuffling sequences for training...
mkdir: cannot create directory ‘tmp_tfrec_/home/ben/Documents/Projects/NLP-binning-approaches/data/Combined_transcripts.fasta’: No such file or directory
./tfrec_train_kmer.sh: line 111: tmp_tfrec_/home/ben/Documents/Projects/NLP-binning-approaches/data/Combined_transcripts.fasta/shuffled_/home/ben/Documents/Projects/NLP-binning-approaches/data/Combined_transcripts.fasta: No such file or directory

./tfrec_train_kmer.sh: line 116: cd: tmp_tfrec_/home/ben/Documents/Projects/NLP-binning-approaches/data/Combined_transcripts.fasta: No such file or directory
split: invalid number of lines: ‘0’: Numerical result out of range
rm: cannot remove 'shuffled_/home/ben/Documents/Projects/NLP-binning-approaches/data/Combined_transcripts.fasta': No such file or directory

3. Converting to TFRecord...
ls: cannot access 'subset*': No such file or directory
Can't use 'defined(@array)' (Maybe you should just omit the defined()?) at /home/ben/Documents/Projects/DeepMicrobes/bin/parallel line 119.
cat: 'subset*.tfrec': No such file or directory
rm: cannot remove 'subset*.tfrec': No such file or directory
rmdir: failed to remove 'tmp_tfrec_/home/ben/Documents/Projects/NLP-binning-approaches/data/Combined_transcripts.fasta': No such file or directory
Finished.

It looks like instead of adding the temporary directories to the end of the given paths its trying to prepend them, which is causing all sorts of issues. Is there something that I am missing?

**Comment by MicrobeLab** [comment]
Yes, you're right. The script assumes that the input fasta (-i) is not a full path. That's why mkdir failed at the beginning. You could modify that line of code to allow the script to add the temporary directories to the end of the given paths. Thanks.
