### ISSUE TITLE
where is tfrec_predict_kmer.sh?

### ISSUE THREAD

**Issue by animesh** [MicrobeLab/DeepMicrobes#9]
Can't seem to find it, all i see with tf* is

```
find . -iname "tf*sh"
./pipelines/tfrec_train_onehot.sh
./pipelines/tfrec_predict_onehot.sh
./pipelines/tfrec_train_kmer.sh
./pipelines/tfrec_predict_kmer.sh
```

**Comment by MicrobeLab** [comment]
https://github.com/MicrobeLab/DeepMicrobes/blob/master/pipelines/tfrec_predict_kmer.sh

Also please refer to the last line of the output from your command line: ./pipelines/tfrec_predict_kmer.sh
